[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore"
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
ignore = [
    "E712",  # at least in policy tests, I want to ensure API returns booleans

    # these are all new lints that fail from ruff 0.15.3 -> 0.16.4 but
    # I don't want to fix them all right now.
    # "in general" PRs accepted to reduce this list by fixing the lints
    "PLE2513",
    "FA100",
    "I001",
    "UP032",
    "C408",
    "BLE001",
    "SIM102",
    "FA102",
    "TRY002",
    "RUF008",
    "RUF009",
    "UP008",
    "PERF102",
    "PIE790",
    "PLR1711",
    "PLR1730",
    "RET501",
    "RUF059",
    "SIM114",
    "UP006",
    "UP012",
    "D419",
    "FURB192",
    "S110",
    "UP004",
    "UP010",
    "UP024",
    "UP025",
    "UP035",
]

[project]
name = "fowl"
dynamic = ["version"]
description = "Forward Over Wormhole Locally provides bi-directional streaming data over secure and durable Dilated magic-wormhole connections. Secure communication with easy setup."
readme = "README.rst"
license = {file = "LICENSE"}
authors = [
    { name = "meejah", email = "meejah@meejah.ca" },
]
requires-python = ">=3.9"
keywords = [
    "cryptography",
    "forwarding",
    "magic-wormhole",
    "private",
]
classifiers = [
    "Framework :: Twisted",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "setuptools",
    "click",
    "attrs",
    "six",
    "msgpack",
    "humanize",
    "twisted",
    "magic-wormhole[dilate] >= 0.20.0",
    "rich",
    "ipaddress",
]

# note: between ruff 0.15.7 and ruff 0.16.4 a lot of new default rules
# were added, and we go from 0 to 417 failing lints.
# for now, pinning to 0.15.7...

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-twisted",
    "pytest-cov",
    "magic-wormhole-mailbox-server >= 0.6.0",
    "cuvner",
    "hypothesis",
    "ruff <= 0.16.3",
]
dev = [
    "twine",
    "sphinx",
    "dulwich",
    "pysequoia",
    "pip-tools",
    "hatch",
    "readme-renderer",
    "cuvner",
]
lint = [
    "ruff <= 0.16.3",
]

[project.scripts]
fowl = "fowl.cli:fowl"
fowld = "fowl.cli:fowld"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "src/fowl/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "src",
    "docs",
    "Makefile",
    "README.rst",
    "pyproject.toml",
    "requirements-pinned.txt",
]
exclude = [
    "*~",
    "*.egg-info*",
]

[tool.coverage.run]
branch = true
parallel = true
source_pkgs = ["fowl"]

## so my weird coverage problem .. was a "coverage combine" when
## there's a "leftover" .coverage.* file
##
## ..i guess "coverage combine" just combines .coverage.* (and NOT including .coverage ??)
