name: Linux Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        # Get enough history for the tags we get next to be meaningful.  0
        # means all history.
        fetch-depth: "0"
        # Checkout head of the branch of the PR, or the exact revision
        # specified for non-PR builds.
        ref: "${{ github.event.pull_request.head.sha || github.sha }}"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --editable .[test]

    - name: pytest
      run: timeout --signal=TERM 60 python -m pytest --cov=fowl -s -v integration/

    - name: Coverage graph
      shell: bash
      run: python -m cuv graph
      continue-on-error: true

    - name: Coverage report
      shell: bash
      run: |
          git diff origin/main..HEAD > p
          python -m cuv report p
      continue-on-error: true
